/*
This file is part of VideoCapturer

VideoCapturer is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

VideoCapturer is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with VideoCapturer.  If not, see <http://www.gnu.org/licenses/>.
 */
/*
 * VideoPanel.java
 *
 * Created on Sep 27, 2012, 6:08:06 PM
 */
package com.deepak.videocapturer.gui;

import com.deepak.videocapturer.core.Camera;
import java.awt.Graphics;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.media.CannotRealizeException;
import javax.media.NoDataSourceException;
import javax.media.NoPlayerException;

/**
 *
 * @author deepak
 */

/*
 * a panel class which provides the display of the captured image
 */
public class VideoPanel extends javax.swing.JPanel {

    // the camera object
    private Camera camera = null;

    /** Creates new form VideoPanel */
    public VideoPanel() {
        initComponents();
        try {
            // create and start camera
            camera = new Camera();
            camera.start();
        } catch (IOException ex) {
            Logger.getLogger(VideoPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoDataSourceException ex) {
            Logger.getLogger(VideoPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoPlayerException ex) {
            Logger.getLogger(VideoPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (CannotRealizeException ex) {
            Logger.getLogger(VideoPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(VideoPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /*
     * on garbage collection stop camera to de-allocate resource
     */
    @Override
    protected void finalize() throws Throwable {
        camera.stop();
    }

    @Override
    public void paint(Graphics g) {
        // get the captured image and display it onto the panel
        g.drawImage(camera.getPicture(), 0, 0, this);
        // repaint the panel for next image
        repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
